baseurl: "/resumecards" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://localhost:4000/resumecards/" # the base hostname & protocol for your site

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"

gems:
  - jekyll-seo-tag

title: "Herman's Resume Card"
description: "iOS/Android App Developer"
author: "Herman Liang"
image: "http://2.gravatar.com/avatar/30d18111643d80b35c6cf11637c00603?s=150"
facebook:
  admins: "roryliang"